# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xd9\x01\n\nCalculator\x12\x31\n\x03\x41\x64\x64\x12\x12.calculator.Number\x1a\x12.calculator.Number\"\x00(\x01\x12\x31\n\x03Sub\x12\x12.calculator.Number\x1a\x12.calculator.Number\"\x00(\x01\x12\x32\n\x04Mult\x12\x12.calculator.Number\x1a\x12.calculator.Number\"\x00(\x01\x12\x31\n\x03\x44iv\x12\x12.calculator.Number\x1a\x12.calculator.Number\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBER']._serialized_start=32
  _globals['_NUMBER']._serialized_end=55
  _globals['_CALCULATOR']._serialized_start=58
  _globals['_CALCULATOR']._serialized_end=275
# @@protoc_insertion_point(module_scope)
